services:
    werkint.proxy:
        class: Werkint\Bundle\ProxyBundle\Service\Proxy
        arguments:
            - @werkint.redis.ns.werkint_proxy
            - %werkint_proxy%
        tags:
            - { name: werkint.redis.cacher, ns: werkint_proxy }